spec: 
  template: 
    spec: 
      containers: 
        - 
          ports: 
            - 
              containerPort: 8080
              name: iso-adapter
              protocol: TCP
          resources: 
            limits: 
              cpu: "1.0"
              memory: 512Mi
            requests: 
              cpu: "0.4"
              memory: 256Mi
